### ISSUE TITLE
Error install mean-cli debian arm platform 

### ISSUE THREAD

**Issue by Xertion57** [linnovate/mean-cli#123]
Hello guys. I'm here because I have an issue installing mean-cli that i couldn't overcome.
The system i'm working on is a beaglebone black (arm) running an 8.2 jessie debian. I'm aware of the legacy binary node issue, I installed node-js-legacy to solve it but it didn't seem to have any effect.
i also tried to make a soft link from node to nodejs, it didn't work.

Here's is the error :
(you can fin the zip log here : [npm-debug.zip](https://github.com/linnovate/mean-cli/files/61412/npm-debug.zip) )

mean-cli@0.10.17 preinstall /usr/local/lib/node_modules/mean-cli
node ./scripts/preinstall

module.js:340
throw err;
^
Error: Cannot find module '/usr/local/lib/node_modules/mean-cli/scripts/preinstall'
at Function.Module._resolveFilename (module.js:338:15)
at Function.Module._load (module.js:280:25)
at Function.Module.runMain (module.js:497:10)
at startup (node.js:119:16)
at node.js:906:3
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! mean-cli@0.10.17 preinstall: node ./scripts/preinstall
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the mean-cli@0.10.17 preinstall script.
npm ERR! This is most likely a problem with the mean-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR! node ./scripts/preinstall
npm ERR! You can get their info via:
npm ERR! npm owner ls mean-cli
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 4.1.12-ti-r29
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mean-cli"
npm ERR! cwd /usr/local/lib
npm ERR! node -v v0.10.38
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR! /usr/local/lib/npm-debug.log
npm ERR! not ok code 0

Anyone would know what's wrong ?
thanks !

**Comment by amanuel2** [comment]
Yes im getting the same problem... Somone please help..

**Comment by Xertion57** [comment]
Hi,

What worked for me, I cannot guarantee the theory behind that but tell me if it worked : 

I made the global packages installation with sudoers permissions.

Then I was making the NPM install with standard user permission. 
I read the errors and it seemed that the npm install was trying to write in usr/local/lib/nodes_modules. I suspect that node-gyp is doing stuff in this folder. (whereas it shouldn't)

Stuffs in this folder are created by the user "nobody" and my user couldn't write on that.

I made an chown -R of /usr/local/lib/nodes_modules then npm install again and everything worked.

**Comment by amanuel2** [comment]
I didnt understand what you said..

**Comment by Xertion57** [comment]
So what now, you expect me to do the questions and the answers ?

**Comment by amanuel2** [comment]
Yes @Xertion57

**Comment by steezeburger** [comment]
He tells you what he did to get his setup to work. You can probably figure it out if you Google some of the keywords.
