### ISSUE TITLE
Error install on Ubuntu 16.04 Xenial LTS

### ISSUE THREAD

**Issue by The-Technicalist** [linnovate/mean-cli#128]
I was trying to install Mean Stack and Mean Cli is one of the npm packages necessary to run a Mean Stack Server.

So upon using
`npm install -g mean-cli`

Its started running good so far and then two warnings popped up
```
npm WARN deprecated json-file-plus@2.0.0: Before v3.0.0, errors in fs.writeFile would not be propagated
npm WARN lifecycle mean-cli@0.11.1~preinstall: cannot run in wd %s %s (wd=%s) mean-cli@0.11.1 node ./scripts/preinstall /usr/local/lib/node_modules/.staging/mean-cli-54905f3b
```

Following those two warnings this was logged
```
/usr/local/bin/mean -> /usr/local/lib/node_modules/mean-cli/bin/mean
/usr/local/bin/mean-init -> /usr/local/lib/node_modules/mean-cli/bin/mean-init
/usr/local/bin/mean-authorize -> /usr/local/lib/node_modules/mean-cli/bin/mean-authorize
/usr/local/bin/mean-whoami -> /usr/local/lib/node_modules/mean-cli/bin/mean-whoami
/usr/local/bin/mean-addKey -> /usr/local/lib/node_modules/mean-cli/bin/mean-addKey
/usr/local/bin/mean-login -> /usr/local/lib/node_modules/mean-cli/bin/mean-login
/usr/local/bin/mean-publish -> /usr/local/lib/node_modules/mean-cli/bin/mean-publish
/usr/local/bin/mean-search -> /usr/local/lib/node_modules/mean-cli/bin/mean-search
/usr/local/bin/mean-register -> /usr/local/lib/node_modules/mean-cli/bin/mean-register
/usr/local/bin/mean-postinstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-postinstall
/usr/local/bin/mean-preinstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-preinstall
/usr/local/bin/mean-install -> /usr/local/lib/node_modules/mean-cli/bin/mean-install
/usr/local/bin/mean-uninstall -> /usr/local/lib/node_modules/mean-cli/bin/mean-uninstall
/usr/local/bin/mean-docs -> /usr/local/lib/node_modules/mean-cli/bin/mean-docs
/usr/local/bin/mean-package -> /usr/local/lib/node_modules/mean-cli/bin/mean-package
/usr/local/bin/mean-list -> /usr/local/lib/node_modules/mean-cli/bin/mean-list
/usr/local/bin/mean-status -> /usr/local/lib/node_modules/mean-cli/bin/mean-status
/usr/local/bin/mean-user -> /usr/local/lib/node_modules/mean-cli/bin/mean-user
/usr/local/bin/mean-logout -> /usr/local/lib/node_modules/mean-cli/bin/mean-logout
/usr/local/bin/mean-disable -> /usr/local/lib/node_modules/mean-cli/bin/mean-disable
/usr/local/bin/mean-enable -> /usr/local/lib/node_modules/mean-cli/bin/mean-enable

> kerberos@0.0.19 install /usr/local/lib/node_modules/mean-cli/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

/bin/sh: 1: node: not found
gyp: Call to 'node -e "require('nan')"' returned exit status 127 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/node-gyp/lib/configure.js:354:16)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.4.0-15-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/mean-cli/node_modules/kerberos
gyp ERR! node -v v4.2.6
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 

> bson-ext@0.1.13 install /usr/local/lib/node_modules/mean-cli/node_modules/bson-ext
> (node-gyp rebuild 2> builderror.log) || (exit 0)


> mean-health@0.1.7 postinstall /usr/local/lib/node_modules/mean-cli/node_modules/mean-health
> node ./postinstall.js

sh: 1: node: not found
/usr/local/lib
└── (empty)

npm ERR! Linux 4.4.0-15-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "mean-cli"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! mean-health@0.1.7 postinstall: `node ./postinstall.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the mean-health@0.1.7 postinstall script 'node ./postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mean-health package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mean-health
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mean-health
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/teknicalist/npm-debug.log
npm ERR! code 1
```

Here is the full log (npm-debug.log) : https://gist.github.com/The-Technicalist/479ce3a786b743ce62ad

**Comment by liorkesos** [comment]
Are you sure you installed node's?
You have a 'node not found' error
Lior

**Comment by The-Technicalist** [comment]
When i run `nodejs --version`
I get `v4.2.6`

Do i need to install nodejs-legacy ?

**Comment by liorkesos** [comment]
It is executing the binary node not node's
Create a symlink or find a more organic Ubuntu alternative
Lior
