### ISSUE TITLE
Cannot find module 'request'

### ISSUE THREAD

**Issue by GodsBreath** [linnovate/mean-cli#131]
I'm receiving the following error when I attempt to run 'mean init':

> module.js:440
>     throw err;
>     ^
> 
> Error: Cannot find module 'request'
>     at Function.Module._resolveFilename (module.js:438:15)
>     at Function.Module._load (module.js:386:25)
>     at Module.require (module.js:466:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/usr/local/lib/node_modules/mean-cli/lib/controllers/anonymized-data.js:8:12)
>     at Module._compile (module.js:541:32)
>     at Object.Module._extensions..js (module.js:550:10)
>     at Module.load (module.js:456:32)
>     at tryModuleLoad (module.js:415:12)
>     at Function.Module._load (module.js:407:3)

For some reason, the request module is not included in the dependencies list for mean-cli. Even when I install the request package manually, whether globally or locally, it does not resolve this issue.

**Comment by GodsBreath** [comment]
I finally figured out what was going on. I had just updated my repository list to point at the NodeSource repository so I could get a more recent version of nodejs and npm (I'm using Ubuntu, and the packages in the Ubuntu repository are woefully outdated.)

The old version of npm was putting binaries in the /usr/local/bin directory and packages the /user/local/lib directory, whereas the newer versions put them in the /usr/bin and /usr/lib folders, respectively. I had installed mean-cli earlier before I upgraded to the newer version of npm, so it was still running based on the old folder structure.
