### ISSUE TITLE
Gulp & npm not found after following installation steps

### ISSUE THREAD

**Issue by ferrybig** [linnovate/mean-cli#148]
Trying to follow the installation steps, this happened:

1. `npm install -g mean-cli`
 
    This works

2. `mean init mean-application`

    This one properly installs a mean application

3. `cd <NameOfYourApp> && npm install`

    Seems to install all packages needed

4. `mean package <NameOfYourPackage>`

```
    Throws:

    module.js:472
    throw err;
    ^

Error: Cannot find module 'npm'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\fernando\AppData\Roaming\npm\node_modules\mean-cli\lib\cli.js:5:7)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```  
5. `gulp` 

    Throws the following error:

```
[10:34:24] Local gulp not found in ~\Documents\Webdesign\mean-application
[10:34:24] Try running: npm install gulp
```

**Comment by yasirunilan** [comment]
Also the installed project doesn't have a gulp file to run the Gulp command. I also tried in my local machine this problem is there for me also.

**Comment by liorkesos** [comment]
Gulp and npm need to be installed globally .
Maybe the prerequisites section in the readme is unclear.
You should probably run
npm install -g gulp
Lior

**Comment by yasirunilan** [comment]
@liorkesos  in my case I have already installed gulp globally. Problem is there is no any gulp file inside the project to run the gulp command.
